jwt:
  secret_key: key
  access_expiration_time: 12h
  refresh_expiration_time: 24h

log:
  level: debug
  disable_sentry: true

db:
  url: db_url

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: voting-svc
  service_port: 80
